### ISSUE TITLE
JDK16 MathLoadTest_all_special_5m_1_FAILED - Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9#13179]
Failure link
------------

https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_special.system_s390x_linux_Personal/8/tapResults/ (`rh7-390-4`)
```
09:27:50  openjdk version "16.0.1-internal" 2021-04-20
09:27:50  OpenJDK Runtime Environment (build 16.0.1-internal+0-adhoc.****.BuildJDK16s390xlinuxPersonal)
09:27:50  Eclipse OpenJ9 VM (build master-d5a8afc9d9c, JRE 16 Linux s390x-64-Bit Compressed References 20210710_32 (JIT enabled, AOT enabled)
09:27:50  OpenJ9   - d5a8afc9d9c
09:27:50  OMR      - bdee22f4b9e
09:27:50  JCL      - 3c4bffefe5e based on jdk-16.0.1+9)
```
[Rerun in Grinder](https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=special.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&TEST_PARALLELIZATION_PARAMS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=s390x_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&BUILD_IDENTIFIER=Custom&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK16_s390x_linux_Personal%2F32%2FOpenJ9-JDK16-s390x_linux-20210710-085517.tar.gz+https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK16_s390x_linux_Personal%2F32%2Ftest-images.tar.gz&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=ci-eclipse-openj9&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=16&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fibmruntimes%2Fopenj9-openjdk-jdk16.git&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=d5a8afc9d9c223462a234448a5b6bf3cd34dfaea&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=openj9&LABEL_ADDITION=&ARTIFACTORY_REPO=ci-openj9&ARTIFACTORY_ROOT_DIR=Test&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=e047f50a-26c4-4b82-8525-6da17ec68450&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=5&OPENJDK_SHA=&TRSS_URL=&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=Dynamic)

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test MathLoadTest_all_special_5m_1 ...
===============================================
MathLoadTest_all_special_5m_1 Start Time: Sat Jul 10 10:38:28 2021 Epoch Time (ms): 1625927908131
variation: Mode103
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs 

MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=effa2270 Signal_Code=00000001
MLT stderr Handler1=000003FFAE047DB8 Handler2=000003FFADF32268 InaccessibleAddress=0074006500730000
MLT stderr gpr0=000000010000001E gpr1=000000010000001E gpr2=000000010000001E gpr3=000003FF00000000
MLT stderr gpr4=000003FF0E2A6200 gpr5=000003FEAC008AC0 gpr6=000003FF26EBB950 gpr7=000003FF293A2C70
MLT stderr gpr8=000003FF2A2132E0 gpr9=000000010000001E gpr10=0074006500730074 gpr11=000003FF26A25618
MLT stderr gpr12=000003FF293A2930 gpr13=000003FFA89F6F00 gpr14=000003FF0F626DD0 gpr15=000003FFADD7E498
MLT stderr psw=000003FF0F626DDA mask=0705200180000000 fpc=0038ff00 bea=000003FF0CA7576C
MLT stderr fpr0 423fb17600000000 (f: 0.000000, d: 1.361213e+11)
MLT stderr fpr1 3e639bd900000000 (f: 0.000000, d: 3.652420e-08)
MLT stderr fpr2 3e3ab28300000000 (f: 0.000000, d: 6.215952e-09)
MLT stderr fpr3 3c974326eb2475ce (f: 3945035264.000000, d: 8.070736e-17)
MLT stderr fpr4 be80df9400000000 (f: 0.000000, d: -1.257163e-07)
MLT stderr fpr5 3e92514600000000 (f: 0.000000, d: 2.729516e-07)
MLT stderr fpr6 3eccd6bc00000000 (f: 0.000000, d: 3.437854e-06)
MLT stderr fpr7 3e3a405f00000000 (f: 0.000000, d: 6.112142e-09)
MLT stderr fpr8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr9 56aaabfc97d6f331 (f: 2547446528.000000, d: 3.131996e+109)
MLT stderr fpr10 0000007400000068 (f: 104.000000, d: 2.461515e-312)
MLT stderr fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr12 000003ffa8303f18 (f: 2821734144.000000, d: 2.172196e-311)
MLT stderr fpr13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=effa4670 Signal_Code=00000001
MLT stderr Handler1=000003FFAE047DB8 Handler2=000003FFADF32268 InaccessibleAddress=0074006500730000
MLT stderr gpr0=000000010000001E gpr1=000000010000001E gpr2=000000010000001E gpr3=000003FF00000000
MLT stderr gpr4=000003FF0E2A6200 gpr5=000003FEB4008650 gpr6=000003FF26EBB950 gpr7=000003FF28F6B2B8
MLT stderr gpr8=000003FF2A211960 gpr9=000000010000001E gpr10=0074006500730074 gpr11=000003FF26A25618
MLT stderr gpr12=000003FF28F39048 gpr13=000003FFA8A05900 gpr14=000003FF0F626DD0 gpr15=000003FFADBC7498
MLT stderr psw=000003FF0F626DDA mask=0705200180000000 fpc=0018ff00 bea=000003FF0CA7576C
MLT stderr 
MLT stderr Compiled_method=net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr Target=2_90_20210710_32 (Linux 3.10.0-1062.18.1.el7.s390x)
MLT stderr CPU=s390x (4 logical CPUs) (0x1ec1c5000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr fpr0 423cd70500000000 (f: 0.000000, d: 1.238665e+11)
MLT stderr fpr1 3e639f5500000000 (f: 0.000000, d: 3.654955e-08)
MLT stderr fpr2 3e3ab28300000000 (f: 0.000000, d: 6.215952e-09)
MLT stderr fpr3 3ca96d80509f79fe (f: 1352628736.000000, d: 1.764404e-16)
MLT stderr fpr4 3ea4da0200000000 (f: 0.000000, d: 6.214259e-07)
MLT stderr fpr5 3e92535800000000 (f: 0.000000, d: 2.730721e-07)
MLT stderr fpr6 3eccd94300000000 (f: 0.000000, d: 3.439030e-06)
MLT stderr fpr7 3e3a43bd00000000 (f: 0.000000, d: 6.115204e-09)
MLT stderr fpr8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr9 56aaabfc97d6f331 (f: 2547446528.000000, d: 3.131996e+109)
MLT stderr fpr10 0000007400000068 (f: 104.000000, d: 2.461515e-312)
MLT stderr fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr12 000003ffa8303f18 (f: 2821734144.000000, d: 2.172196e-311)
MLT stderr fpr13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr 
MLT stderr Compiled_method=net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr Target=2_90_20210710_32 (Linux 3.10.0-1062.18.1.el7.s390x)
MLT stderr CPU=s390x (4 logical CPUs) (0x1ec1c5000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=effa6e70 Signal_Code=00000001
MLT stderr Handler1=000003FFAE047DB8 Handler2=000003FFADF32268 InaccessibleAddress=0074006500730000
MLT stderr gpr0=000000010000001E gpr1=000000010000001E gpr2=000000010000001E gpr3=000003FF00000000
MLT stderr gpr4=000003FF0E2A6200 gpr5=000003FEA8008C10 gpr6=000003FF26EBB950 gpr7=000003FF27B575F0
MLT stderr gpr8=000003FF2A1EFD80 gpr9=000000010000001E gpr10=0074006500730074 gpr11=000003FF26A25618
MLT stderr gpr12=000003FF27784260 gpr13=000003FFA89FEF00 gpr14=000003FF0F626DD0 gpr15=000003FFADCFE498
MLT stderr psw=000003FF0F626DDA mask=0705200180000000 fpc=0038ff00 bea=000003FF0CA7576C
MLT stderr fpr0 000000000000babe (f: 47806.000000, d: 2.361930e-319)
MLT stderr fpr1 3e63932b00000000 (f: 0.000000, d: 3.646105e-08)
MLT stderr fpr2 3e3ab28300000000 (f: 0.000000, d: 6.215952e-09)
MLT stderr fpr3 3c36f84e509f79fe (f: 1352628736.000000, d: 1.245203e-18)
MLT stderr fpr4 3e6a532300000000 (f: 0.000000, d: 4.903367e-08)
MLT stderr fpr5 3e924c1e00000000 (f: 0.000000, d: 2.726515e-07)
MLT stderr fpr6 3eccd06f00000000 (f: 0.000000, d: 3.434920e-06)
MLT stderr fpr7 3e3a37fc00000000 (f: 0.000000, d: 6.104514e-09)
MLT stderr fpr8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr9 56aaabfc97d6f331 (f: 2547446528.000000, d: 3.131996e+109)
MLT stderr fpr10 0000007400000068 (f: 104.000000, d: 2.461515e-312)
MLT stderr fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr12 000003ffa8303f18 (f: 2821734144.000000, d: 2.172196e-311)
MLT stderr fpr13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr 
MLT stderr Compiled_method=net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr Target=2_90_20210710_32 (Linux 3.10.0-1062.18.1.el7.s390x)
MLT stderr CPU=s390x (4 logical CPUs) (0x1ec1c5000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x000003FF0F626DDA [<unknown>+0x0])
MLT stderr ---------------------------------------
MLT stderr (0x000003FF0F626DDA [<unknown>+0x0])
MLT stderr ---------------------------------------
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/07/10 10:39:45 - please wait.
MLT stderr (0x000003FF0F626DDA [<unknown>+0x0])
MLT stderr ---------------------------------------
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/07/10 10:39:45 - please wait.
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/07/10 10:39:45 - please wait.
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0001.dmp' in response to an event
MLT 10:39:50.856 - Completed 20.2%. Number of tests started=99 (+38)
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0001.dmp
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0004.txt' in response to an event
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0003.dmp' in response to an event
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0004.txt
STF 10:40:01.722 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0004.txt
STF 10:40:01.722 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0001.dmp
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0004.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0001.dmp
MLT 10:40:10.886 - Completed 26.9%. Number of tests started=99 (+0)
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0003.dmp
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0006.txt' in response to an event
MLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/Snap.20210710.103945.54406.0005.trc' in response to an event
MLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/Snap.20210710.103945.54406.0005.trc
MLT stderr JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/jitdump.20210710.103945.54406.0007.dmp' in response to an event
MLT stderr JVMDUMP051I JIT dump occurred in 'load-1' thread 0x000003FFA89FEF00
MLT stderr JVMDUMP053I JIT dump is recompiling net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0006.txt
STF 10:40:16.254 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0006.txt
STF 10:40:16.254 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0003.dmp
STF 10:40:16.254 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/Snap.20210710.103945.54406.0005.trc
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/javacore.20210710.103945.54406.0006.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/core.20210710.103945.54406.0003.dmp
MLT stderr Snap file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/results/Snap.20210710.103945.54406.0005.trc
MLT stderr JVMDUMP013I Processed dump event "gpf", detail "".
STF 10:40:16.756 - **FAILED** Process MLT ended with exit code (255) and not the expected exit code/s (0)
STF 10:40:16.756 - Monitoring Report Summary:
STF 10:40:16.756 -   o Process MLT has crashed unexpectedly
STF 10:40:16.756 - Killing processes: MLT
STF 10:40:16.756 -   o Process MLT pid 54406 is not running
**FAILED** at step 1 (Run math load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/../TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/execute.pl line 94.
STF 10:40:17.256 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 10:40:17.256 - 
STF 10:40:17.256 - ====================   T E A R D O W N   ====================
STF 10:40:17.256 - Running teardown: perl /home/jenkins/workspace/Test_openjdk16_j9_special.system_s390x_linux_Personal_testList_3/aqa-tests/TKG/../TKG/output_16259240137989/MathLoadTest_all_special_5m_1/20210710-103828-MathLoadTest/tearDown.pl
STF 10:40:17.286 - TEARDOWN stage completed
STF 10:40:17.288 - 
STF 10:40:17.288 - =====================   R E S U L T S   =====================
STF 10:40:17.288 - Stage results:
STF 10:40:17.288 -   setUp:     pass
STF 10:40:17.288 -   execute:  *fail*
STF 10:40:17.288 -   teardown:  pass
STF 10:40:17.288 - 
STF 10:40:17.288 - Overall result: **FAILED**

MathLoadTest_all_special_5m_1_FAILED
```

Similar error occurred at `MathLoadTest_bigdecimal_special_5m_1`, `MathLoadTest_all_special_5m_4`, `MathLoadTest_all_special_5m_6`, `LambdaLoadTest_special_J9_5m_4`, etc.

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@nbhuiyan Please take a look

**Comment by nbhuiyan** [comment]
Should be fixed via #13281

**Comment by pshipton** [comment]
There were still failures on the weekend run, which contain https://github.com/eclipse-openj9/openj9/pull/13281
https://openj9-jenkins.osuosl.org/job/Test_openjdk16_j9_special.system_ppc64_aix_Personal/12
```
OpenJ9: d903a99
OMR: ef9fafc
OpenJDK16: ee030f1 - openj9-openjdk-jdk16
```

**Comment by JasonFengJ9** [comment]
Similar segmentation error is observed at `Test_openjdk16_j9_special.system_ppc64le_linux_Personal/7/tapResults/` (`sles15le-rt1-1`)
```
===============================================
Running test MathLoadTest_all_special_5m_1 ...
===============================================
MathLoadTest_all_special_5m_1 Start Time: Sun Aug 22 23:02:08 2021 Epoch Time (ms): 1629698528368
variation: Mode103
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xjit:count=0 -Xnocompressedrefs 

MLT 23:02:43.147 -   103 ArbitraryJava[net.adoptopenjdk.test.autosimd.AutoSIMDTestLong testSums]  Weighting=1 
MLT 23:02:43.147 -   104 JUnit[net.adoptopenjdk.test.math.MathAPITest]  Weighting=1 
MLT 23:02:45.208 - Starting thread. Suite=0 thread=0
MLT 23:02:45.264 - Starting thread. Suite=0 thread=1
MLT 23:02:45.264 - Starting thread. Suite=0 thread=2
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000003
MLT stderr Handler1=00007FFF9BB64910 Handler2=00007FFF9BA9C300
MLT stderr R0=00007FFF034C86AC R1=00007FFEC8CEB740 R2=00007FFF9BD66E00 R3=000000010000006A
MLT stderr R4=00007FFF1EF83BF0 R5=00007FFF1EF83BA0 R6=FFFFFFFFFFFFFFFF R7=00007FFF01300038
MLT stderr R8=00007FFE9C007B70 R9=000000000000000E R10=00007FFF034C86AC R11=00007FFF9C8CEFC0
MLT stderr R12=0000000082004842 R13=00007FFEC8CF68F0 R14=00007FFE9C007B50 R15=00007FFF9CA26100
MLT stderr R16=00007FFF01300038 R17=FFFFFFFFFFFFFFFF R18=0000000000000002 R19=0000000000000000
MLT stderr R20=00007FFF9C1C76A8 R21=00007FFF1E6D7D48 R22=0000000000000000 R23=00007FFF1EF83BA0
MLT stderr R24=00007FFF1E443578 R25=00007FFF1EF83BA0 R26=00007FFF1DDBFF20 R27=00007FFF1EDD2DD0
MLT stderr R28=00007FFF1DCC7E18 R29=00007FFF1E443038 R30=0074007300650074 R31=00007FFF1EF83BF0
MLT stderr NIP=00007FFF034C86B8 MSR=800000010280F033 ORIG_GPR3=00007FFF9B25DAC4 CTR=00007FFF034C86AC
MLT stderr LINK=00007FFF9B25DAC8 XER=0000000000000000 CCR=0000000082004844 SOFTE=0000000000000001
MLT stderr TRAP=0000000000000380 DAR=00740073006500C4 dsisr=0000000042000000 RESULT=0000000000000000
MLT stderr FPR0 00007ffe9c007b70 (f: 2617277184.000000, d: 6.953061e-310)
MLT stderr FPR1 4053777a00000000 (f: 0.000000, d: 7.786682e+01)
MLT stderr FPR2 3fc2f112e0000000 (f: 3758096384.000000, d: 1.479820e-01)
MLT stderr FPR3 3fc39a09e0000000 (f: 3758096384.000000, d: 1.531384e-01)
MLT stderr FPR4 3fd24924a0000000 (f: 2684354560.000000, d: 2.857143e-01)
MLT stderr FPR5 3fd99999a0000000 (f: 2684354560.000000, d: 4.000000e-01)
MLT stderr FPR6 3fe5555560000000 (f: 1610612736.000000, d: 6.666667e-01)
MLT stderr FPR7 3f27beb8a0000000 (f: 2684354560.000000, d: 1.811600e-04)
MLT stderr FPR8 0074007300650074 (f: 6619252.000000, d: 1.780215e-306)
MLT stderr FPR9 006d006500740049 (f: 7602249.000000, d: 1.290611e-306)
MLT stderr FPR10 003000300030005f (f: 3145823.000000, d: 8.900703e-308)
MLT stderr FPR11 37f0001d00000000 (f: 0.000000, d: 2.938817e-39)
MLT stderr FPR12 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
MLT stderr FPR13 4028000000000000 (f: 0.000000, d: 1.200000e+01)
MLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr 
MLT stderr Compiled_method=net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr Target=2_90_20210822_35 (Linux 4.12.14-122.80-default)
MLT stderr CPU=ppc64le (4 logical CPUs) (0x1f1370000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x00007FFF034C86B8 [<unknown>+0x0])
MLT stderr (0x00007FFF9BC894E8 [libj9vm29.so+0x1694e8])
MLT stderr (0x00007FFF9BB39450 [libj9vm29.so+0x19450])
MLT stderr (0x00007FFF9BBD43B0 [libj9vm29.so+0xb43b0])
MLT stderr (0x00007FFF9BA9D708 [libj9prt29.so+0x3d708])
MLT stderr (0x00007FFF9BBCF564 [libj9vm29.so+0xaf564])
MLT stderr (0x00007FFF9BA313E8 [libj9thr29.so+0x113e8])
MLT stderr (0x00007FFFA0C4AA48 [libpthread.so.0+0xaa48])
MLT stderr clone+0xe4 (0x00007FFFA0B57394 [libc.so.6+0x117394])
MLT stderr ---------------------------------------
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/22 23:02:47 - please wait.
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000003
MLT stderr Handler1=00007FFF9BB64910 Handler2=00007FFF9BA9C300
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000003
MLT stderr Handler1=00007FFF9BB64910 Handler2=00007FFF9BA9C300
MLT stderr R0=00007FFF034C86AC R1=00007FFEC8D6B740 R2=00007FFF9BD66E00 R3=000000010000006A
MLT stderr R4=00007FFF1EFC6970 R5=00007FFF1EFC6920 R6=FFFFFFFFFFFFFFFF R7=00007FFF01300038
MLT stderr R8=00007FFEA8007B70 R9=000000000000000E R10=00007FFF034C86AC R11=00007FFF9C8CEFC0
MLT stderr R12=0000000082004842 R13=00007FFEC8D768F0 R14=00007FFEA8007B50 R15=00007FFF9CA1E900
MLT stderr R16=00007FFF01300038 R17=FFFFFFFFFFFFFFFF R18=0000000000000002 R19=0000000000000000
MLT stderr R20=00007FFF9C1C76A8 R21=00007FFF1E6ED7A0 R22=0000000000000000 R23=00007FFF1EFC6920
MLT stderr R24=00007FFF1E4C96B8 R25=00007FFF1EFC6920 R26=00007FFF1DDBFE00 R27=00007FFF1EDD2DD0
MLT stderr R28=00007FFF1DCC7E18 R29=00007FFF1E45F0B8 R30=0074007300650074 R31=00007FFF1EFC6970
MLT stderr R0=00007FFF034C86AC R1=00007FFEC8DEB740 R2=00007FFF9BD66E00 R3=000000010000006A
MLT stderr R4=00007FFF1EF9A230 R5=00007FFF1EF9A1E0 R6=FFFFFFFFFFFFFFFF R7=00007FFF01300038
MLT stderr R8=00007FFEA4007B70 R9=000000000000000E R10=00007FFF034C86AC R11=00007FFF9C8CEFC0
MLT stderr R12=0000000082004842 R13=00007FFEC8DF68F0 R14=00007FFEA4007B50 R15=00007FFF9CA16600
MLT stderr R16=00007FFF01300038 R17=FFFFFFFFFFFFFFFF R18=0000000000000002 R19=0000000000000000
MLT stderr R20=00007FFF9C1C76A8 R21=00007FFF1E6D91A0 R22=0000000000000000 R23=00007FFF1EF9A1E0
MLT stderr R24=00007FFF1E4DFE50 R25=00007FFF1EF9A1E0 R26=00007FFF1DDBFE90 R27=00007FFF1EDD2DD0
MLT stderr R28=00007FFF1DCC7E18 R29=00007FFF1E459D78 R30=0074007300650074 R31=00007FFF1EF9A230
MLT stderr NIP=00007FFF034C86B8 MSR=800000010280F033 ORIG_GPR3=00007FFF9B25DAC4 CTR=00007FFF034C86AC
MLT stderr LINK=00007FFF9B25DAC8 XER=0000000000000000 CCR=0000000082004844 SOFTE=0000000000000001
MLT stderr TRAP=0000000000000380 DAR=00740073006500C4 dsisr=0000000042000000 RESULT=0000000000000000
MLT stderr NIP=00007FFF034C86B8 MSR=800000010280F033 ORIG_GPR3=00007FFF9B25DAC4 CTR=00007FFF034C86AC
MLT stderr LINK=00007FFF9B25DAC8 XER=0000000000000000 CCR=0000000082004844 SOFTE=0000000000000001
MLT stderr TRAP=0000000000000380 DAR=00740073006500C4 dsisr=0000000040000000 RESULT=0000000000000000
MLT stderr FPR0 00007ffea8007b70 (f: 2818603776.000000, d: 6.953071e-310)
MLT stderr FPR1 4053783660000000 (f: 1610612736.000000, d: 7.787832e+01)
MLT stderr FPR2 3fc2f112e0000000 (f: 3758096384.000000, d: 1.479820e-01)
MLT stderr FPR3 3fc39a09e0000000 (f: 3758096384.000000, d: 1.531384e-01)
MLT stderr FPR4 3fd24924a0000000 (f: 2684354560.000000, d: 2.857143e-01)
MLT stderr FPR5 3fd99999a0000000 (f: 2684354560.000000, d: 4.000000e-01)
MLT stderr FPR6 6574203a20646574 (f: 543450496.000000, d: 5.219543e+180)
MLT stderr FPR7 2e74656e28383030 (f: 674771008.000000, d: 6.561917e-85)
MLT stderr FPR8 0074007300650074 (f: 6619252.000000, d: 1.780215e-306)
MLT stderr FPR9 006d006500740049 (f: 7602249.000000, d: 1.290611e-306)
MLT stderr FPR10 003100300030005f (f: 3145823.000000, d: 9.456971e-308)
MLT stderr FPR11 37f0001d00000000 (f: 0.000000, d: 2.938817e-39)
MLT stderr FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR13 3feec709e0000000 (f: 3758096384.000000, d: 9.617967e-01)
MLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR0 00007ffea4007b70 (f: 2751494912.000000, d: 6.953067e-310)
MLT stderr FPR1 40537782e0000000 (f: 3758096384.000000, d: 7.786736e+01)
MLT stderr FPR2 3fc2f112e0000000 (f: 3758096384.000000, d: 1.479820e-01)
MLT stderr FPR3 3fc39a09e0000000 (f: 3758096384.000000, d: 1.531384e-01)
MLT stderr FPR4 3fd24924a0000000 (f: 2684354560.000000, d: 2.857143e-01)
MLT stderr FPR5 3fd99999a0000000 (f: 2684354560.000000, d: 4.000000e-01)
MLT stderr FPR6 3fe5555560000000 (f: 1610612736.000000, d: 6.666667e-01)
MLT stderr FPR7 3f27beb8a0000000 (f: 2684354560.000000, d: 1.811600e-04)
MLT stderr FPR8 0074007300650074 (f: 6619252.000000, d: 1.780215e-306)
MLT stderr FPR9 006d006500740049 (f: 7602249.000000, d: 1.290611e-306)
MLT stderr FPR10 003000300030005f (f: 3145823.000000, d: 8.900703e-308)
MLT stderr FPR11 37f0001d00000000 (f: 0.000000, d: 2.938817e-39)
MLT stderr FPR12 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
MLT stderr FPR13 3feec709e0000000 (f: 3758096384.000000, d: 9.617967e-01)
MLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr 
MLT stderr Compiled_method=net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr 
MLT stderr Compiled_method=net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr Target=2_90_20210822_35 (Linux 4.12.14-122.80-default)
MLT stderr Target=2_90_20210822_35 (Linux 4.12.14-122.80-default)
MLT stderr CPU=ppc64le (4 logical CPUs) (0x1f1370000 RAM)
MLT stderr CPU=ppc64le (4 logical CPUs) (0x1f1370000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x00007FFF034C86B8 [<unknown>+0x0])
MLT stderr (0x00007FFF9BC894E8 [libj9vm29.so+0x1694e8])
MLT stderr (0x00007FFF9BB39450 [libj9vm29.so+0x19450])
MLT stderr (0x00007FFF9BBD43B0 [libj9vm29.so+0xb43b0])
MLT stderr (0x00007FFF9BA9D708 [libj9prt29.so+0x3d708])
MLT stderr (0x00007FFF9BBCF564 [libj9vm29.so+0xaf564])
MLT stderr (0x00007FFF034C86B8 [<unknown>+0x0])
MLT stderr (0x00007FFF9BA313E8 [libj9thr29.so+0x113e8])
MLT stderr (0x00007FFF9BC894E8 [libj9vm29.so+0x1694e8])
MLT stderr (0x00007FFFA0C4AA48 [libpthread.so.0+0xaa48])
MLT stderr (0x00007FFF9BB39450 [libj9vm29.so+0x19450])
MLT stderr clone+0xe4 (0x00007FFFA0B57394 [libc.so.6+0x117394])
MLT stderr (0x00007FFF9BBD43B0 [libj9vm29.so+0xb43b0])
MLT stderr ---------------------------------------
MLT stderr (0x00007FFF9BA9D708 [libj9prt29.so+0x3d708])
MLT stderr (0x00007FFF9BBCF564 [libj9vm29.so+0xaf564])
MLT stderr (0x00007FFF9BA313E8 [libj9thr29.so+0x113e8])
MLT stderr (0x00007FFFA0C4AA48 [libpthread.so.0+0xaa48])
MLT stderr clone+0xe4 (0x00007FFFA0B57394 [libc.so.6+0x117394])
MLT stderr ---------------------------------------
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/22 23:02:47 - please wait.
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/08/22 23:02:47 - please wait.
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0001.dmp' in response to an event
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0001.dmp
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0004.txt' in response to an event
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0002.dmp' in response to an event
STF 23:02:48.185 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0004.txt
STF 23:02:48.186 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0001.dmp
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0004.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0001.dmp
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0002.dmp
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0004.txt
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0005.txt' in response to an event
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0003.dmp' in response to an event
STF 23:02:49.240 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0005.txt
STF 23:02:49.241 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0002.dmp
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0005.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0002.dmp
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0003.dmp
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0007.txt' in response to an event
MLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/Snap.20210822.230247.9064.0006.trc' in response to an event
MLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/Snap.20210822.230247.9064.0006.trc
MLT stderr JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/jitdump.20210822.230247.9064.0008.dmp' in response to an event
MLT stderr JVMDUMP051I JIT dump occurred in 'load-2' thread 0x00007FFF9CA26100
MLT stderr JVMDUMP053I JIT dump is recompiling net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
STF 23:02:49.964 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0007.txt
STF 23:02:49.964 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0003.dmp
STF 23:02:49.965 - Found dump at: /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/Snap.20210822.230247.9064.0006.trc
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0007.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/core.20210822.230247.9064.0003.dmp
MLT stderr Snap file generated - /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/Snap.20210822.230247.9064.0006.trc
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0005.txt
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/javacore.20210822.230247.9064.0007.txt
MLT stderr JVMDUMP053I JIT dump is recompiling net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.addResult(Ljava/lang/String;Ljava/lang/String;Lorg/junit/runner/Description;Ljava/lang/String;Ljava/lang/Throwable;)V
MLT stderr JVMDUMP053I JIT dump is recompiling net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor$1.testFinished(Lorg/junit/runner/Description;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runner/notification/SynchronizedRunListener.testFinished(Lorg/junit/runner/Description;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runner/notification/RunNotifier$7.notifyListener(Lorg/junit/runner/notification/RunListener;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runner/notification/RunNotifier$SafeNotifier.run()V
MLT stderr JVMDUMP053I JIT dump is recompiling junit/framework/TestResult.endTest(Ljunit/framework/Test;)V
MLT stderr JVMDUMP053I JIT dump is recompiling junit/framework/TestResult.run(Ljunit/framework/TestCase;)V
MLT stderr JVMDUMP053I JIT dump is recompiling junit/framework/TestCase.run(Ljunit/framework/TestResult;)V
MLT stderr JVMDUMP053I JIT dump is recompiling junit/framework/TestSuite.run(Ljunit/framework/TestResult;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/internal/runners/JUnit38ClassRunner.run(Lorg/junit/runner/notification/RunNotifier;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runners/ParentRunner$3.run()V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runners/ParentRunner.runChildren(Lorg/junit/runner/notification/RunNotifier;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runners/ParentRunner$2.evaluate()V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runners/ParentRunner.run(Lorg/junit/runner/notification/RunNotifier;)V
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runner/JUnitCore.run(Lorg/junit/runner/Runner;)Lorg/junit/runner/Result;
MLT stderr JVMDUMP053I JIT dump is recompiling org/junit/runner/JUnitCore.run(Lorg/junit/runner/Request;)Lorg/junit/runner/Result;
MLT stderr JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/results/jitdump.20210822.230247.9064.0008.dmp
MLT stderr JVMDUMP013I Processed dump event "gpf", detail "".
STF 23:02:54.607 - **FAILED** Process MLT ended with exit code (255) and not the expected exit code/s (0)
STF 23:02:54.607 - Monitoring Report Summary:
STF 23:02:54.607 -   o Process MLT has crashed unexpectedly
STF 23:02:54.608 - Killing processes: MLT
STF 23:02:54.608 -   o Process MLT pid 9064 is not running
**FAILED** at step 1 (Run math load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/../TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/execute.pl line 94.
STF 23:02:54.778 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 23:02:54.779 - 
STF 23:02:54.779 - ====================   T E A R D O W N   ====================
STF 23:02:54.779 - Running teardown: perl /home/jenkins/workspace/Test_openjdk16_j9_special.system_ppc64le_linux_Personal_testList_0/aqa-tests/TKG/../TKG/output_16296868891775/MathLoadTest_all_special_5m_1/20210822-230208-MathLoadTest/tearDown.pl
STF 23:02:54.902 - TEARDOWN stage completed
STF 23:02:54.911 - 
STF 23:02:54.911 - =====================   R E S U L T S   =====================
STF 23:02:54.911 - Stage results:
STF 23:02:54.911 -   setUp:     pass
STF 23:02:54.911 -   execute:  *fail*
STF 23:02:54.911 -   teardown:  pass
STF 23:02:54.911 - 
STF 23:02:54.911 - Overall result: **FAILED**

MathLoadTest_all_special_5m_1_FAILED
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=eclipse&BUILD_LIST=system&PLATFORM=ppc64le_linux&TARGET=MathLoadTest_bigdecimal_special_5m_4)

**Comment by JasonFengJ9** [comment]
Closing it as per comment above for now. (can re-open if it appears again)

**Comment by JasonFengJ9** [comment]
A similar segmentation error is observed at latest JDK16 build  `Test_openjdk16_j9_special.system_aarch64_linux_testList_4/44/tapResults/`
```
===============================================
Running test MathLoadTest_all_special_5m_6 ...
===============================================
MathLoadTest_all_special_5m_6 Start Time: Thu Sep  2 01:57:07 2021 Epoch Time (ms): 1630562227361
variation: Mode121
JVM_OPTIONS:  -Xgcpolicy:optavgpause -Xjit:count=0 -Xnocompressedrefs 

openjdk version "16.0.2-ea" 2021-07-20
IBM Semeru Runtime Open Edition 16.0.2.1 (build 16.0.2-ea+7)
Eclipse OpenJ9 VM 16.0.2.1 (build master-c0440c463, JRE 16 Linux aarch64-64-Bit Compressed References 20210902_72 (JIT enabled, AOT enabled)
OpenJ9   - c0440c463
OMR      - c42f7f657
JCL      - 44316ee515 based on jdk-16.0.2+7)

MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
MLT stderr Handler1=0000FFFF9CC01828 Handler2=0000FFFF9CB77660 InaccessibleAddress=0000000000000020
MLT stderr R0=0000FFFEFFE79480 R1=0000FFFEFFE79490 R2=0000FFFEF8037020 R3=0000FFFEF8069600
MLT stderr R4=0000FFFF07F867B4 R5=0000000000000000 R6=0000000000000000 R7=0000FFFF97FF03D8
MLT stderr R8=0000FFFEFFDA7990 R9=0000FFFF000CC78C R10=0000FFFF07F867BC R11=0000000000000028
MLT stderr R12=0000FFFF264CA8F8 R13=0000FFFF1AA14038 R14=0000000000000006 R15=0000FFFEFC874110
MLT stderr R16=0000FFFF9CB4D118 R17=0000FFFF9DA6C428 R18=0000FFFF9CBBD000 R19=0000FFFEFFE79480
MLT stderr R20=0000FFFEF8037020 R21=0000000000000000 R22=0000FFFF07F867B4 R23=0000000000000000
MLT stderr R24=0000FFFF07F867BC R25=0000000000000000 R26=0000000000000001 R27=0000FFFF9801B3F8
MLT stderr R28=0000FFFF98A43D00 R29=0000FFFF980245E0 R30=0000FFFF97D4288C R31=0000FFFEFC873E20
MLT stderr PC=0000FFFF97D42890 SP=0000FFFEFC873E20 PSTATE=0000000020000000
MLT stderr V0 0000000000000003 (f: 3.000000, d: 1.482197e-323)
MLT stderr V1 000000003e3ab283 (f: 1044034176.000000, d: 5.158214e-315)
MLT stderr V2 3ebce40000000000 (f: 0.000000, d: 1.722015e-06)
MLT stderr V3 bfe0039525501f33 (f: 626007872.000000, d: -5.004373e-01)
MLT stderr V4 bfd00ea348b88334 (f: 1220051712.000000, d: -2.508934e-01)
MLT stderr V5 3fd5575b0be00b6a (f: 199232368.000000, d: 3.334568e-01)
MLT stderr V6 bfdffffef20a4123 (f: 4060758272.000000, d: -4.999997e-01)
MLT stderr V7 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
MLT stderr V8 3fe62e42fefa39ef (f: 4277811712.000000, d: 6.931472e-01)
MLT stderr V9 406ff262073071c9 (f: 120615368.000000, d: 2.555745e+02)
MLT stderr V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V16 bff0000000000000 (f: 0.000000, d: -1.000000e+00)
MLT stderr V17 feff000000000000 (f: 0.000000, d: -5.314683e+303)
MLT stderr V18 0000fffefc873fe0 (f: 4236722176.000000, d: 1.390650e-309)
MLT stderr V19 0000fffefc873fd0 (f: 4236722176.000000, d: 1.390650e-309)
MLT stderr V20 0000fffefc873fc0 (f: 4236722176.000000, d: 1.390650e-309)
MLT stderr V21 0000fffefc873fb0 (f: 4236722176.000000, d: 1.390650e-309)
MLT stderr V22 0000fffefc873fa0 (f: 4236722176.000000, d: 1.390650e-309)
MLT stderr V23 00000000000000f0 (f: 240.000000, d: 1.185758e-321)
MLT stderr V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr V29 401aaaaaaaaaaaab (f: 2863311616.000000, d: 6.666667e+00)
MLT stderr V30 401c000000000000 (f: 0.000000, d: 7.000000e+00)
MLT stderr V31 0000000041040000 (f: 1090781184.000000, d: 5.389175e-315)
MLT stderr Module=/home/jenkins/workspace/Test_openjdk16_j9_special.system_aarch64_linux_testList_4/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so
MLT stderr Module_base_address=0000FFFF9763B000
MLT stderr Target=2_90_20210902_72 (Linux 4.15.0-112-generic)
MLT stderr CPU=aarch64 (8 logical CPUs) (0x1f2618000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x0000FFFF9CB742B8 [libj9prt29.so+0x262b8])
MLT stderr ---------------------------------------
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2021/09/02 02:02:34 - please wait.

STF 03:04:22.223 - Overall result: **FAILED**

MathLoadTest_all_special_5m_6_FAILED
```
[Re-run the Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=ibm&BUILD_LIST=system&PLATFORM=aarch64_linux&TARGET=MathLoadTest_all_special_5m_6)

Re-opening..
fyi @nbhuiyan

**Comment by fengxue-IS** [comment]
Verified **MathLoadTest_all_special_5m_1** 20/20 passed on s390_linux `Grinder/17942/`
@nbhuiyan can you confirm if the aarch64 failure is same as #13431, if so, this can be closed

**Comment by JasonFengJ9** [comment]
Since this `MathLoadTest` segmentation error is only observed at `aarch64`, track it w/ #13431 instead.

Closing..
