### ISSUE TITLE
Power Linux/AIX invalid page size errors

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse-openj9/openj9#22143]
There are a number of AIX and Linux on P failures in the OMR Acceptance build. All seem to be related to requesting different page sizes. Seems to affect all JDK levels. One example only,
```
 [ERR] 2: j9vmem_testFindValidPageSize(64K large page size)
 [ERR] 	/home/jenkins/workspace/Build_JDK17_ppc64le_linux_OMR/openj9/runtime/tests/port/j9vmemTest.c line 1917: Expected j9vmem_find_valid_page_size() to return pageSize: 0x10000, pageFlags: 0x1, but found pageSize: 0x1000, pageFlags: 0x1
 [ERR] 
 [ERR] 		LastErrorNumber: -108
 [ERR] 		LastErrorMessage: No such file or directory
```

One example build showing the error:
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_OMR_testList_1/629/consoleFull

**Comment by 0xdaryl** [comment]
A recent change affecting this area of code was introduced in https://github.com/eclipse-omr/omr/pull/7795.

**Comment by zl-wang** [comment]
i think these are not real failures, but are side-effects of artificial pagesize set-up in `omr/fvtest/porttest/omrvmemTest.cpp`
especially looking at the failure message on Linux where we know for a fact that 4KB and 16GB pages are not supported (hardware can support them, but OS never expose them), the portLib native test cases still are able to find them (because of the artificial/faked set-up).

while we need to fix the native test cases in a reasonable way, could we promote the build in the mean time if these are all the failures there to be?

**Comment by zl-wang** [comment]
artificial in the sense:  the pagesize array are filled in by the test code itself, rather than being queried from the OS.
@luke-li-2003  could you double-check on AIX failures if it is due to the same problem?

**Comment by luke-li-2003** [comment]
I can confirm that the AIX fail ([like this one](https://openj9-jenkins.osuosl.org/view/Test_Functional_OMR/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/724/consoleText)) is the same case: the test expects the hard-coded check to reject the 16G page size, but with the hard-coded check removed, the code now allows it since it is in the page list.

**Comment by 0xdaryl** [comment]
Thanks for the investigation.  Can you repair the test cases so they function correctly?  

We have not promoted OMR for nearly two weeks.  I am willing (with @pshipton's approval) to promote OMR with these failures on the condition that the tests be fixed.  Inspecting the failures in the OMR Acceptance build is unfortunately more manual than it should be, but be that as it may, the tests should be fixed to reflect current operation.  Please confirm @luke-li-2003 @zl-wang

**Comment by pshipton** [comment]
We can't accept failures in sanity.functional testing, unless you are willing to ignore these tests on these platforms until they can be fixed. Or volunteering to do the triage across these platforms all versions to determine if there are any other failures in the nightly builds.

**Comment by 0xdaryl** [comment]
I'd rather the tests be fixed to take human intervention out of this as much as possible.  We'll wait on promoting until the tests are fixed.

**Comment by luke-li-2003** [comment]
This PR (https://github.com/eclipse-openj9/openj9/pull/22176) should update the testing code so that the test can pass.

**Comment by jdmpapin** [comment]
I believe this is fixed now that #22176 has been merged

**Comment by pshipton** [comment]
There are still failures on AIX.

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_0/1037
xlpCodeCacheTests_1
```
03:51:12  command: /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_0/jdkbinary/j2sdk-image/bin/java  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump -Xms64m -Xmx64m -verbose:sizes -Xlp16G -classpath /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_0/aqa-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar j9vm.test.xlpcodecache.XlpCodeCacheOptionsTest 
03:51:12  
03:51:12    -Xmca32K        RAM class segment increment
03:51:12    -Xmco128K       ROM class segment increment
03:51:12    -Xmcrs0K        compressed references metadata initial size
03:51:12    -Xmns16M        initial new space size
03:51:12    -Xmnx16M        maximum new space size
03:51:12    -Xms64M         initial memory size
03:51:12    -Xmos48M        initial old space size
03:51:12    -Xmox48M        maximum old space size
03:51:12    -Xmx64M         memory maximum
03:51:12    -Xmr4K          remembered set size
03:51:12    -Xlp:objectheap:pagesize=16G	 large page size
03:51:12                    available large page sizes:
03:51:12                    4K
03:51:12                    64K
03:51:12                    16M
03:51:12                    16G
03:51:12    -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
03:51:12                    available large page sizes for JIT code cache:
03:51:12                    4K
03:51:12                    64K
03:51:12                    16M
03:51:12                    16G
03:51:12    -Xmso512K       operating system thread stack size
03:51:12    -Xiss2K         java thread stack initial size
03:51:12    -Xssi16K        java thread stack increment
03:51:12    -Xss1M          java thread stack maximum size
03:51:12    -XX:SharedCacheHardLimit=300M shared class cache size
03:51:12    -Xscmx64M       shared class cache soft max size
03:51:12    -Xscdmx24544K   reserved shared class cache space for class debug attributes
03:51:12    -Xscminaot0K    min reserved shared class cache space for AOT
03:51:12    -Xscmaxaot282300K max allowed shared class cache space for AOT
03:51:12    -Xscminjitdata0K min reserved shared class cache space for JIT data
03:51:12    -Xscmaxjitdata282300K max allowed shared class cache space for JIT data
03:51:12  A message from XlpCodeCacheOptionsTest class
03:51:12  ERROR: Page size and type in Xlp:codecache option is not same as used by JIT, but the expected warning message is not found
03:51:12  	Page size and page type in Xlp:codecache option: 17179869184 not used
03:51:12  	Page size and page type used by JIT: 4096 not used
03:51:12  *** Test FAILED *** (j9vm.test.xlpcodecache.XlpCodeCacheOptionsTest)
```

https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Nightly_testList_1/1039/
xlpCodeCacheTests_3

https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/1006
17 failed to run
https://openj9-jenkins.osuosl.org/job/Test_openjdk21_j9_extended.functional_ppc64_aix_Nightly/491

**Comment by pshipton** [comment]
Exclude the tests on AIX until they can be fixed.
https://github.com/eclipse-openj9/openj9/pull/22189

**Comment by 0xdaryl** [comment]
@luke-li-2003 : could you look into these latest failures please?

**Comment by luke-li-2003** [comment]
The new failures are not a problem with the tests like the previous ones, but because the option parsing facility cannot handle a 16G page size request.

This should fix it: https://github.com/eclipse-openj9/openj9/pull/22190

**Comment by 0xdaryl** [comment]
Fixed by #22190.
